USE [master]
GO
/****** Object:  Database [Practika]    Script Date: 21.12.2024 1:34:27 ******/
CREATE DATABASE [Practika]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Practika', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.DIPTISA\MSSQL\DATA\Practika.mdf' , SIZE = 466944KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Practika_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.DIPTISA\MSSQL\DATA\Practika_log.ldf' , SIZE = 270336KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Practika] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Practika].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Practika] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Practika] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Practika] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Practika] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Practika] SET ARITHABORT OFF 
GO
ALTER DATABASE [Practika] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Practika] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Practika] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Practika] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Practika] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Practika] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Practika] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Practika] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Practika] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Practika] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Practika] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Practika] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Practika] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Practika] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Practika] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Practika] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Practika] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Practika] SET RECOVERY FULL 
GO
ALTER DATABASE [Practika] SET  MULTI_USER 
GO
ALTER DATABASE [Practika] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Practika] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Practika] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Practika] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Practika] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Practika] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Practika', N'ON'
GO
ALTER DATABASE [Practika] SET QUERY_STORE = ON
GO
ALTER DATABASE [Practika] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Practika]
GO
/****** Object:  Table [dbo].[categ]    Script Date: 21.12.2024 1:34:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[categ](
	[id] [int] NOT NULL,
	[category_name] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_categ] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[order]    Script Date: 21.12.2024 1:34:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[order](
	[id] [int] NOT NULL,
	[product_id] [int] NOT NULL,
	[user_id] [int] NOT NULL,
	[price] [decimal](18, 2) NOT NULL,
	[count] [int] NULL,
	[sum] [decimal](18, 2) NULL,
	[date] [datetime] NULL,
 CONSTRAINT [PK_order] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[prodact]    Script Date: 21.12.2024 1:34:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[prodact](
	[id] [int] NOT NULL,
	[name_prod] [nvarchar](max) NOT NULL,
	[id_cat] [int] NOT NULL,
 CONSTRAINT [PK_prodact] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[user2]    Script Date: 21.12.2024 1:34:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[user2](
	[id] [int] NOT NULL,
	[family_name] [nvarchar](max) NOT NULL,
	[first_name] [nvarchar](max) NOT NULL,
	[patronymic] [nvarchar](max) NOT NULL,
	[login] [nvarchar](max) NOT NULL,
	[password] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_user2] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[users]    Script Date: 21.12.2024 1:34:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[users](
	[id] [int] NOT NULL,
	[family_name] [nvarchar](max) NOT NULL,
	[first_name] [nvarchar](max) NOT NULL,
	[patronymic] [nvarchar](max) NOT NULL,
	[login] [nvarchar](max) NOT NULL,
	[password] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_users] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[order]  WITH CHECK ADD  CONSTRAINT [FK_order_prodact] FOREIGN KEY([product_id])
REFERENCES [dbo].[prodact] ([id])
GO
ALTER TABLE [dbo].[order] CHECK CONSTRAINT [FK_order_prodact]
GO
ALTER TABLE [dbo].[order]  WITH CHECK ADD  CONSTRAINT [FK_order_users] FOREIGN KEY([user_id])
REFERENCES [dbo].[users] ([id])
GO
ALTER TABLE [dbo].[order] CHECK CONSTRAINT [FK_order_users]
GO
ALTER TABLE [dbo].[prodact]  WITH CHECK ADD  CONSTRAINT [FK_prodact_categ] FOREIGN KEY([id_cat])
REFERENCES [dbo].[categ] ([id])
GO
ALTER TABLE [dbo].[prodact] CHECK CONSTRAINT [FK_prodact_categ]
GO
USE [master]
GO
ALTER DATABASE [Practika] SET  READ_WRITE 
GO
