//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PraktikaPP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;

    public partial class PractikaDB : DbContext
    {
        public PractikaDB()
            : base("name=PractikaDB")
        {
        }
        private static PractikaDB _context;

        public static PractikaDB GetContext()
        {
            if (_context == null)
                _context = new PractikaDB();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<categ> categ { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<prodact> prodact { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user2> user2 { get; set; }
        public virtual DbSet<users> users { get; set; }

    }
}